
BOARD = stm32f4_discovery
PROJECT_NAME = led-blink-demo

SOURCE = main.c

USE_FREERTOS = 1
USE_MINSTDLIBS = 1
USE_DRIVER_LEDS = 1

USE_FULL_ASSERT = 1
	
STM32DEVSUPPORTDIR = ../..
include $(STM32DEVSUPPORTDIR)/stm32-build-env/setup.mk