
BOARD = stm32f4_discovery
PROJECT_NAME = led-blink-demo

SOURCE = main.c

USE_PTHREADS = 1
USE_FREERTOS = 1
USE_MINLIBC = 1
USE_DRIVER_LEDS = 1

USE_FULL_ASSERT = 1
DEBUG_PRINTF_EXCEPTIONS = 1
	
LIKEPOSIX_DIR = ../../like-posix
include $(LIKEPOSIX_DIR)/build-env/setup.mk